# Generated by Django 5.0.1 on 2024-01-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('passengers', models.IntegerField(default=0)),
            ],
        ),
    ]
